<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The layer of the neural net that data is passed into.
### Hidden Layer: A layer of the neural netowork that is between the input and output layer that is not manually configured
### Output Layer: The layer of a network that provides the output. 
### Neuron: A cell of a layer that is connected to other neurons using weights
### Weight: The amount that the input from a neuron is changed before being passed along to the next layer
### Activation Function: the activation function is how the neuron is scaled down to being on a a 0-1 pattern. It informs what the actuall value passed along to the next weight will be
### Node Map: a node map is a drawing that lays out the neurons and connections in a neural net 
### Perceptron: the most basic neural net which takes in a series of inputs and produces a single output. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

the inputs are fist passed into the input layer of the neural net. Then each input is multiplied by the weight and then summed. The bias is then added to this sum and it is passed through an activation funtion. the output from that then becomes the input for the next neuron. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [14]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [15]:
##### Your Code Here #####
def sigmoid(data):
    return 1/(1+np.exp(-data))
def sigmoid_derivative(data):
    sx=sigmoid(data)
    return sx*(1-sx)

In [16]:
import numpy as np

In [17]:
sigmoid(1)

0.7310585786300049

In [18]:
sigmoid_derivative(sigmoid(1))

0.2193618640098077

In [19]:
#this randomly generates numbers from -1 to 1 
weights=2*np.random.random((2,1))-1

In [20]:
weights

array([[ 0.50886568],
       [-0.11671779]])

In [21]:
2*np.random.random((2,1))

array([[0.21933595],
       [1.29833076]])

In [64]:
inputs=df[['x1', 'x2']].values

In [23]:
#apply the weights and sum it up
weighted_sum=np.dot(inputs, weights)

In [24]:
weighted_sum

array([[ 0.        ],
       [ 0.50886568],
       [-0.11671779],
       [ 0.39214789]])

In [25]:
#apply the activation function
activated_output=sigmoid(weighted_sum)

In [26]:
#because the weights were assigned randomly this output is garbage 
activated_output

array([[0.5       ],
       [0.62454053],
       [0.47085363],
       [0.59679965]])

In [27]:
actual=[[1],[1],[1],[0]]
error=actual-activated_output

In [28]:
#see? totally random error and output 
error

array([[ 0.5       ],
       [ 0.37545947],
       [ 0.52914637],
       [-0.59679965]])

In [29]:
#find how to adjust the weights
adjustment= error * sigmoid_derivative(activated_output)
adjustment

array([[ 0.11750186],
       [ 0.08527559],
       [ 0.12521716],
       [-0.13666539]])

In [30]:
weights+= np.dot(inputs.T, adjustment)
weights


array([[ 0.45747588],
       [-0.12816602]])

In [31]:
AND=np.array([[1, 1],[1,0],[0,1],[0,0]])
AND

array([[1, 1],
       [1, 0],
       [0, 1],
       [0, 0]])

In [32]:
actual=[[1],[0],[0],[0]]

In [33]:
inputs

x1  x2
0   0   0
1   1   0
2   0   1
3   1   1

In [34]:
new=np.array([[1],[1],[1],[1]])
np.append(AND, new,1)

array([[1, 1, 1],
       [1, 0, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [35]:
def perceptronStep(inputs, weights, bias):
    #get the sum of the inputs and weights
#     biases=np.array([[1],[1],[1],[1]])
#     inputs=np.append(inputs, biases, 1)
    weighted_sum=np.dot(inputs, weights)+bias
    #pass them through an activation funtion 
    activated_output=sigmoid(weighted_sum)
    #calculate error versus actual 
    error=actual - activated_output
    #do backprop/gradient descent magic
    adjustment=error*sigmoid_derivative(activated_output)
    weights += np.dot(inputs.T, adjustment)
    #return the new weights to run again
    bias+=error
    return weights, bias 

In [36]:
weights=2*np.random.random((2,1))-1
bias=2*np.random.random((4,1))-1
print(weights)
for i in range(50000):
    weights, bias=perceptronStep(inputs, weights, bias)
print(weights)
activated_output=sigmoid(np.dot(inputs,weights[0:2]))
print(activated_output)

[[-0.60254591]
 [-0.20269035]]
[[-3.51257767]
 [-3.1208906 ]]
[[0.5       ]
 [0.02895647]
 [0.04225372]
 [0.00131386]]


In [37]:
inputs

x1  x2
0   0   0
1   1   0
2   0   1
3   1   1

In [38]:
actual=[[1],[1],[1], [0]]
#np.dot(inputs, weights)

In [40]:
weights=2*np.random.random((2,1))-1
#but why four? that doesn't make any sense
bias=2*np.ones((4,1))-1
for i in range(10000):
    weighted_sum=np.dot(inputs, weights)+bias
    activated_output=sigmoid(weighted_sum)
    error = actual - activated_output
    adjustments= error*sigmoid_derivative(activated_output)
    weights += np.dot(inputs.T, adjustments)
    bias+=error

In [65]:
weights=2*np.random.random((3,1))-1
#bias=2*np.random.random((4,1))-1
inputs=df[['x1', 'x2']].values
inputs=np.append(inputs, np.ones((4,1)), axis=1)
for i in range(10000):
    weighted_sum=np.dot(inputs, weights)
    activated_output=sigmoid(weighted_sum)
    error = actual - activated_output
    adjustments= error*sigmoid_derivative(activated_output)
    weights += np.dot(inputs.T, adjustments)

In [66]:
print(weights)
print(bias)
print(activated_output)

[[-11.84024224]
 [-11.84024224]
 [ 17.80922778]]
[[ 9.2101899 ]
 [ 9.65022716]
 [ 9.91934742]
 [-8.06350707]]
[[0.99999998]
 [0.99744943]
 [0.99744943]
 [0.00281168]]


In [60]:
inputs=np.append(inputs, np.ones((4,1)), axis=1)


In [61]:
inputs

array([[0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#I got nothing on how to make that one work so I went on the internet to find one

In [48]:
class Perceptron(object):
    def __init__(self, no_inputs, threshold=100, learning_rate=.1):
        self.threshold = threshold
        self.learning_rate=learning_rate
        self.weights = np.zeros(no_inputs+1)
        
    def train(self, training_inputs, labels):
        '''This function doesn't use a sigmoid function, instead it just does a binary classification by saying anything 
        positive is one and anything negative is 0. I am going to try to impliment sigmoid functions if I can get it to 
        work like this first'''
        for _ in range(self.threshold):
            for inputs, label in zip(training_inputs, labels):
                prediction=self.predict(inputs)
                self.weights[1:] += self.learning_rate*(label-prediction)*inputs
                self.weights[0] += self.learning_rate*(label-prediction)
    
    def predict(self, inputs):
        summation=np.dot(inputs, self.weights[1:])+self.weights[0]
        if summation>0:
            return 1
        else: 
            return 0

In [51]:
precept=Perceptron(3)
precept.train(AND, actual)

ValueError: shapes (2,) and (3,) not aligned: 2 (dim 0) != 3 (dim 0)

In [50]:
class Perceptron(object):

    def __init__(self, no_of_inputs, threshold=100, learning_rate=0.01):
        self.threshold = threshold
        self.learning_rate = learning_rate
        self.weights = np.zeros(no_of_inputs + 1)
           
    def predict(self, inputs):
        summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
        if summation > 0:
          activation = 1
        else:
          activation = 0            
        return activation

    def train(self, training_inputs, labels):
        for _ in range(self.threshold):
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learning_rate * (label - prediction) * inputs
                self.weights[0] += self.learning_rate * (label - prediction)

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [23]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [24]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [25]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

IndentationError: expected an indented block (<ipython-input-25-057d68540610>, line 6)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?