<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
##### Your Code Here #####
import numpy as np
class Network:
    def __init__(self):
        #build the network nodes
        self.inputNodes=3
        self.hiddenNodes=5
        self.outputNodes=1
        
        #set up the weights, plus 1 for bias 
        #input to hidden layer
        self.weights1=np.random.rand(self.inputNodes+1, self.hiddenNodes)
        #hidden to output
        self.weights2=np.random.rand(self.hiddenNodes+1, self.outputNodes)
    
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s*(1-s)
    
    def predict(self, X):
        #apply the bias
        X=np.append(X, np.ones((7,1)), axis=1)
        #get the weighted sums going into the hidden layer
        self.hidden_sum=np.dot(X, self.weights1)
        #pass through activation 
        self.active_hidden=self.sigmoid(self.hidden_sum)
        self.output_sum=np.dot(self.active_hidden, self.weights2[1:])+self.weights2[0]
        self.activated_out=self.sigmoid(self.output_sum)
        return self.activated_out
    
    def backProp(self, X, y, o):
        #find the output error 
        self.o_error=y-o
        #adjustments for the output layer weights
        self.o_adjustment=self.o_error * self.sigmoidPrime(o)
        
        self.z2_error= self.o_adjustment.dot(self.weights2[1:].T)
        #adjustments for input to hidden layer weights
        self.z2_adjustments = self.z2_error *self.sigmoidPrime(self.active_hidden)
        #apply the adjustments
        X=np.append(X, np.ones((7,1)), axis=1)
        self.weights1+=X.T.dot(self.z2_adjustments)
        self.active_hidden=np.append(self.active_hidden, np.ones((7,1)), axis=1)
        self.weights2+=self.active_hidden.T.dot(self.o_adjustment)
        
    def train(self, X, y):
        o=self.predict(X)
        self.backProp(X, y, o)

In [2]:
    def backward(self, X, y, o):
        
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) # adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) # adjust second set (hidden => output) weights

In [3]:
nn=Network()

In [4]:
inputs=np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1],
    [0,0,0]])


In [5]:
actual=np.array([[0],[1],[1],[1],[1],[0],[0]])

In [6]:
out=nn.predict(inputs)
out

array([[0.82769123],
       [0.84787186],
       [0.84526618],
       [0.82715459],
       [0.82691673],
       [0.8597499 ],
       [0.79889495]])

In [7]:
#I don't know why this doesn't work 
nn.backProp(inputs, actual, out)

In [8]:
for _ in range(100000):
    nn.train(inputs, actual)
nn.predict(inputs)

array([[9.20888021e-04],
       [9.99174736e-01],
       [9.55350503e-01],
       [1.00000000e+00],
       [9.55810747e-01],
       [6.34868062e-02],
       [3.21387611e-04]])

In [9]:
X=inputs
y=actual

for epoch in range(1000):
    nn.train(X, y)
    print('+' + '---' * 3 + f'EPOCH {epoch+1}' + '---'*3 + '+')
    print('Input: \n', X)
    print('Actual Output: \n', y)
    print('Weights1: ', nn.weights1)
    print('Weights2:', nn.weights2)
    print('Predicted Output: \n', str(nn.predict(X)))
    print('Loss: \n', str(np.mean(np.square(y - nn.predict(X)))))

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Weights1:  [[  7.53881675   8.4539817    8.30905029  -8.4902323    1.65590563]
 [  3.1945398  -12.86496252  -4.58765381  10.93549856   2.55011639]
 [  0.39558651  -1.2249572    1.77519269   1.11668574   1.78634797]
 [  4.03908628  -1.13333098   6.53138552   2.23034197   6.6737333 ]]
Weights2: [[   4.68512413]
 [ 408.41824515]
 [   3.85655538]
 [-422.26637084]
 [  -1.93349038]
 [   8.39246385]]
Predicted Output: 
 [[9.20882187e-04]
 [9.99174740e-01]
 [9.55350522e-01]
 [1.00000000e+00]
 [9.55810761e-01]
 [6.34867820e-02]
 [3.21384713e-04]]
Loss: 
 0.0011397812243579824
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Weights1:  [[  7.5388284    8.45398625   8.30905948  -8.49023829   1.65590996]
 [  3.19453954 -12.8649792   -4.5876509

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [10]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [11]:
# input image dimensions
img_rows, img_cols = 28, 28

In [12]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [13]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [14]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [15]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [16]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [26]:
class minstNetwork:
    def __init__(self):
        #build the network nodes
        self.inputNodes=784
        self.hiddenNodes=16
        self.outputNodes=1
        
        #set up the weights, plus 1 for bias 
        #input to hidden layer
        self.weights1=np.random.rand(self.inputNodes+1, self.hiddenNodes)
        #hidden to output
        self.weights2=np.random.rand(self.hiddenNodes+1, self.outputNodes)
    
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s*(1-s)
    
    def predict(self, X):
        #apply the bias
        X=np.append(X, np.ones((1,1)))
        #get the weighted sums going into the hidden layer
        self.hidden_sum=np.dot(X, self.weights1)
        #pass through activation 
        self.active_hidden=self.sigmoid(self.hidden_sum)
        self.output_sum=np.dot(self.active_hidden, self.weights2[1:])+self.weights2[0]
        self.activated_out=self.sigmoid(self.output_sum)
        return self.activated_out
    
    def backProp(self, X, y, o):
        #find the output error 
        self.o_error=y-o
        #adjustments for the output layer weights
        self.o_adjustment=self.o_error * self.sigmoidPrime(o)
        
        self.z2_error= self.o_adjustment.dot(self.weights2[1:].T)
        #adjustments for input to hidden layer weights
        self.z2_adjustments = self.z2_error *self.sigmoidPrime(self.active_hidden)
        #apply the adjustments
        X=np.append(X, np.ones((1,1)))
        print(self.weights1.shape, X.shape, self.z2_adjustments.shape)
        self.weights1+=X.T.dot(self.z2_adjustments)
        self.active_hidden=np.append(self.active_hidden, np.ones((7,1)), axis=1)
        self.weights2+=self.active_hidden.T.dot(self.o_adjustment)
        
    def train(self, X, y):
        o=self.predict(X)
        self.backProp(X, y, o)

In [27]:
##### Your Code Here #####

nn=minstNetwork()
for i in range(1000):
    print('epoch', i)
    for row, actual in zip(x_train, y_train):
        nn.train(row, actual)
    


epoch 0
(785, 16) (785,) (16,)


ValueError: shapes (785,) and (16,) not aligned: 785 (dim 0) != 16 (dim 0)

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?